### ISSUE TITLE
Support logging to file

### ISSUE THREAD

**Issue by ksilisk** [ksilisk/leetty#39]
Need to add functionality to logging all service to file (location to file should be configurable)

File with logs should store on device not in docker container

**Comment by ksilisk** [comment]
Logs files should be grouped by day

**Comment by ksilisk** [comment]
For logging to file using rolling appender need add this props to application.yaml or .properties
```
logging:
  logback:
    rollingpolicy:
      max-history: 30
  file:
    path: /web_service_logs
```
logging.file.path depends on service
More info about logging [here in spring docs](https://docs.spring.io/spring-boot/reference/features/logging.html)
